# Generated by Django 4.1.4 on 2023-03-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_blog_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='bno',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
